#!/usr/bin/env bash
# Usage: buildkite build
# Summary: Build the docker image needed for running the tools

set -eo pipefail

git submodule update --init --recursive
docker-compose build

cd internal-certificates
docker-compose build
docker-compose run --rm minica /root/fetch-root-cert.sh
cd -
