#!/usr/bin/env bash
# Usage: buildkite build
# Summary: Build the docker image needed for running the tools

set -eo pipefail

#git submodule update --init --recursive
#docker-compose build

cd internal-certificates
echo "Be sure to have set AWS_ACCESS_KEY_ID et al, for the shared-services account (e.g. using aws-vault)"
docker-compose build
cd -
