#!/usr/bin/env bash
# Usage: buildkite cfn [action]
# Summary: Manage Cloudformation stack for Buildkite
# Help:
#
#   Available actions: apply
#
# Examples:
#
# buildkite cfn apply

set -eo pipefail

case "$1" in
--complete)
  echo apply
  ;;
apply)
  docker-compose run --rm infrastructure_tools
  ;;
*)
  buildkite help cfn
  ;;
esac
