version: '3.7'

services:
  infrastructure_tools:
    init: true
    image: 644358627301.dkr.ecr.ap-southeast-2.amazonaws.com/oculo/infrastructure_sceptre:latest
    volumes:
      - .:/sceptre
    working_dir: /sceptre
    command: >
      sh -c "merge-cfn-templates --cfn_templates_directory /sceptre/templates/services && 
      sceptre --var aws_region=ap-southeast-2 launch services --yes"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=ap-southeast-2